### ISSUE TITLE
Show the user if email is already in Database

### ISSUE THREAD

**Issue by RonShk** [RonShk/carScraper#6]
In the server I am returning a status code specific to say that an email is already in the database I believe the code is 409 but check the server code to make sure. If that specific status code is sent to the client then display to the user that the email they are using is already registered with an account

**Comment by arav-sharma** [comment]
Done https://github.com/RonShk/carScraper/pull/8

**Comment by arav-sharma** [comment]
Done https://github.com/RonShk/carScraper/pull/8
